server:
  port: 8085

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/employee-api
    username: employee-api
    password: aaa
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        generate_statistics: true
        use_sql_comments: true

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate: DEBUG
    com.martikan.employeeapi: DEBUG
    org.springframework.jdbc: DEBUG